################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.c \
../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.c 

OBJS += \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.o \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.o 

C_DEPS += \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.d \
./CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_add_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_init_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_inverse_f64.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_fast_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_mult_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_scale_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_sub_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_f32.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q15.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.o: ../CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.c CMSIS/DSP/Source/MatrixFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DARM_MATH_CM4 -DDEBUG -DSTM32F407xx -D__FPU_PRESENT -c -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/DSP/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/DSP_K" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Core/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Sokolov/Documents/GitHub/Asynchronous_drive_stand/Drivers/CMSIS/Include" -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"CMSIS/DSP/Source/MatrixFunctions/arm_mat_trans_q31.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

